# Generated by Django 2.1.9 on 2019-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='contacts_time',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='info_time',
            field=models.BigIntegerField(default=-1),
        ),
    ]
